name: "\U0001F41B Bug, Broken Link, or Outdated Content"
description: Report a bug, broken link, or outdated content in the guide
labels: bug
body:
  - type: input
    id: page
    attributes:
      label: Page or Section
      description: Which page or section is affected? (e.g., manual_annotation.md#2d)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue in detail. If it's a broken link, paste the link. If outdated content, please explain what is wrong or missing.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce (if applicable)
      description: If this is a bug, provide steps to reproduce it.
    validations:
      required: false

