name: Feature Request (New Task or Tool)
description: Suggest a new analysis task, tool, or other feature for the guide
labels: enhancement
body:
  - type: input
    id: feature-title
    attributes:
      label: Title
      description: Short title for your feature request
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the new task, tool, or feature you would like to see added. Include relevant links if available.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature important? How will it help users?
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References or Links (optional)
      description: Add any relevant references, documentation, or links here.
    validations:
      required: false
